name: smoke_free
description: Quit smoking cigarrettes.

publish_to: 'none'

version: 1.0.1
environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.2
  shared_preferences: ^2.1.0
  intl: ^0.19.0
  flutter_hooks: ^0.18.0
  fl_chart: ^0.45.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
